#!/bin/bash

TRASH_DIR="${HOME}/.trash/"

if [ ! -d $TRASH_DIR ]; then
    mkdir $TRASH_DIR
fi

if [ -e $1 ]; then
    mv $1 $TRASH_DIR
else
    echo "ERROR: No such file or directory (${1}"
fi

exit 0

