#!/bin/bash

TRASH_DIR="${HOME}/.trash/"

mv $1 $TRASH_DIR

exit 0

# [[WIP]]
# if [ ! -d $TRASH_DIR ]; then
#     echo test
#     mkdir $TRASH_DIR
# fi
# echo test2
# 
# if [ -e $1 ]; then
#     mv $1 $TRASH_DIR
# else
#     echo "ERROR: No such file or directory (${1}"
# fi
# 
